# Среда сборки
image: Visual Studio 2022

# Версия Python
environment:
  matrix:
    - PYTHON: "C:\\Python311"
      PYTHON_VERSION: "3.11"

# Скрипты для запуска деплоя
build_script:
  - pip install -r requirements.txt

